dist: bionic
language: minimal
env:
  - WORKSHOP_NAME=example-workshop
  - WORKSHOP_NAME=ansible-for-devops
  - WORKSHOP_NAME=better-together
stages:
  - test
  - name: deploy
    if: branch = master
before_script:
  # https://github.com/containers/libpod/blob/master/install.md#ubuntu
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common uidmap curl
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update -qq
  - sudo apt-get -qq -y install podman
  - sudo mkdir -p /etc/containers
  - echo -e "[registries.search]\nregistries = ['docker.io', 'quay.io']" | sudo tee /etc/containers/registries.conf
script: hack/run.sh ${WORKSHOP_NAME} local ${QUAY_REPOSITORY:-creynold} && sleep 10 && curl localhost:8888 || exit 1
jobs:
  include:
    - stage: deploy
      script: bash hack/build.sh ${WORKSHOP_NAME} quay ${QUAY_REPOSITORY:-creynold}
      env: WORKSHOP_NAME=ansible-for-devops
    - stage: deploy
      script: bash hack/build.sh ${WORKSHOP_NAME} quay ${QUAY_REPOSITORY:-creynold}
      env: WORKSHOP_NAME=better-together
